### ISSUE TITLE
2.1 HTML templates

### ISSUE THREAD

**Issue by krijnhoetmer** [Murderlon/browser-technologies#2]
> A bit arbitrary this but IE9 doens't support innerHTML

Are you sure? I believe MS even invented innerHTML way back.

**Comment by Murderlon** [comment]
> The property innerHTML are read-only for the following html objects:
COL, COLGROUP, FRAMESET, HEAD, HTML, STYLE, TABLE, TBODY, TFOOT, THEAD, TITLE, TR
and trying to update the value of their innerHTML property will give you ‘unknown runtime error’ in IE browser. - http://www.ideyatech.com/solution-for-innerhtml-ie-browser-tables/

**Comment by krijnhoetmer** [comment]
Whoah, TIL! Thanks!
